name: jest-tests
on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
